"""initial schema

Revision ID: a9c0a7d895d5
Revises: 
Create Date: 2026-06-22 21:11:34.303178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9c0a7d895d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.execute("""
    CREATE INDEX idx_chunk_doc_active
    ON doc_chunk_registry (doc_id)
    WHERE status = 'active'
    """)
    
    op.execute("""
    CREATE INDEX idx_chunk_embedding
    ON doc_chunk_registry
    USING hnsw (embedding vector_cosine_ops)
    WHERE status = 'active'
    """)
    
    op.execute("""
    CREATE INDEX idx_chunk_bm25_text
    ON doc_chunk_registry
    USING gin (to_tsvector('english', chunk_text))
    """)
        
    op.execute("""
    INSERT INTO index_alias(alias_name,index_version)
    VALUES ('current','v1')
    ON CONFLICT (alias_name) DO NOTHING
    """)
    
    
    
    op.create_table('documents',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('index_alias',
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.Column('index_version', sa.String(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('alias_name')
    )
    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('docs_indexed', sa.Integer(), nullable=False),
    sa.Column('docs_same', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('retrieval_traces',
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('index_version', sa.String(), nullable=False),
    sa.Column('embedding_latency_ms', sa.Integer(), nullable=True),
    sa.Column('retrieval_latency_ms', sa.Integer(), nullable=True),
    sa.Column('rerank_latency_ms', sa.Integer(), nullable=True),
    sa.Column('llm_latency_ms', sa.Integer(), nullable=True),
    sa.Column('chunks_retrieved', sa.JSON(), nullable=True),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_table('doc_chunk_registry',
    sa.Column('chunk_vector_id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('section_heading', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('doc_version', sa.Integer(), nullable=False),
    sa.Column('index_version', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('valid_from', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ),
    sa.PrimaryKeyConstraint('chunk_vector_id'),
    sa.UniqueConstraint('doc_id', 'chunk_index', 'doc_version', 'index_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_chunk_registry')
    op.drop_table('retrieval_traces')
    op.drop_table('ingestion_runs')
    op.drop_table('index_alias')
    op.drop_table('documents')
    # ### end Alembic commands ###
